PBCKP-2705: Add PostgreSQL core patch for fixing build with REL_18
In commit 760162f user-callable CRC functions were added.
Since pg_probackup uses pg_crc.c from the PostgreSQL source,
this change is leading to the undefined reference to pg_detoast_datum_packed errors during the build.
See also https://www.postgresql.org/message-id/flat/ME0P300MB0445018F5C924B2D88983F45B66CA%40ME0P300MB0445.AUSP300.PROD.OUTLOOK.COM